### ISSUE TITLE
Clearing objects

### ISSUE THREAD

**Issue by FxMadness** [erwin-beckers/SimpleTrendReversalEA#1]
You are clearing objects running from 0 to ObjectsTotal() but ObjectsTotal() is dynamic.
To avoid issues with that it is better to run from ObjectTotal() to 0 (i--).

**Comment by erwin-beckers** [comment]
if you check the code you will see that i delete 1 object and then leave the for loop to check objectstotal() again

`
   bool deleted = false;
   do {
      deleted = false;
      for (int i = 0; i < ObjectsTotal();++i)
      {
         string name = ObjectName(0, i);
         if (StringSubstr(name, 0, 1) == "_")
         {
            ObjectDelete(0, name);
            deleted = true;
            break;
         }
      }
   } while (deleted); 
`

**Comment by FxMadness** [comment]
Oops.
